; SIKAMOT-V2 — IoT Motor Ignition via RFID
; Board: ESP32 DEVKITC V4 WROOM-32D
; Branch spi  → PN532 via SPI  (DIP: SW1=ON  SW2=OFF)
; Branch i2c  → PN532 via I2C  (DIP: SW1=OFF SW2=ON)

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
    adafruit/Adafruit PN532@^1.2.4
    bblanchon/ArduinoJson@^6.21.5
    ayushsharma82/ElegantOTA@^3.1.5
